name: Publicar paquete en GitHub Packages
on:
  push:
    branches:
      - main
jobs:
  publicar-paquete:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      # Configure .npmrc file for publishing to GitHub Packages
      # The setup-node action creates an .npmrc file in the runner.
      # When you use the scope input in the setup-node action, the .npmrc file includes the scope prefix.
      # Use the token from the NODE_AUTH_TOKEN environment variable (actually GITHUB_TOKEN) as a reference
      - name: Configure .npmrc
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          # User or organization that owns the workflow
          scope: '@StvanLeo'

      - name: Install dependencies using package-lock.json versions
        run: npm ci
      - name: Publish the package to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}